version: "3"
services:
  image-upload:
    build:
      context: ./imageUpload
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  image-download:
    build:
      context: ./imageDownload
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
